### ISSUE TITLE
Non-TypeScript sample

### ISSUE THREAD

**Issue by mbana** [alexandrudima/monaco-editor-samples#2]
Hi,

Could you please possibly publish an example that doesn't use TypeScript? I ask because it seems like TypeScript (the name at least) is referenced in core. I could be mis-understanding this entirely, so please correct me, but it seems like TypeScript is core and not a plugin?

I can't find a monaco-editor-core repo. I assume this is intentional?

**Comment by alexandrudima** [comment]
Please see https://github.com/Microsoft/monaco-editor#issues

the monaco-editor is stitched together from:
* monaco-editor-core
* monaco-typescript
* monaco-languages
