### ISSUE TITLE
Is this repo moving? (broken link)

### ISSUE THREAD

**Issue by nwolverson** [alexandrudima/monaco-editor-samples#3]
I notice at https://github.com/Microsoft/monaco-editor there is a link to mono-editor-samples which is broken. But that repo has issues disabled (apologies for raising here). I'd imagine either that link should point here, or you were intending moving this repo over also.

**Comment by alexandrudima** [comment]
Yes, I'm about to move this repo too. Sorry about that! :)

**Comment by nwolverson** [comment]
Cheers, obviously I found it anyway (and samples work great).
